server:
  port: 8084
  
spring:
  application:
    name: API-GATEWAY
    
    
  cloud:
    gateway:
      routes:
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
          - path=/quiz/**, /quiz-test/**
            
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
 
